### ISSUE TITLE
Upgrade Fails

### ISSUE THREAD

**Issue by devtrix** [dzimchuk/experimental-tools#11]
### Installed product versions
- Visual Studio: [example 2015 Ultimate ]
- This extension: [example 0.8.76]

### Description
While updating from Version 0.7.69 to 0.8.76, I get "This extension is not supported on the current product." 

### Steps to recreate
1. Tools --> Extensions & Updates
2. Go to the Visual Studio Gallery section under Updates since it shows that there is one.
3. Click the Update button.
4. Update downloads &, EULA shown.  Click Install.

### Current behavior
It has had no issues till now.
### Expected behavior
Upgrade to 0.8.76
![exception](https://cloud.githubusercontent.com/assets/1081747/23460492/aa45d974-fe53-11e6-9f1f-d75464960963.png)

**Comment by dzimchuk** [comment]
@devtrix Yup, I uploaded VS2017 version by mistake. It's now back to VS2015 on the gallery with version 0.8.77. Please let me know if you are able to update. Sorry for inconvenience...

**Comment by dzimchuk** [comment]
VS2015 version of the extension has been renamed as 'Experimental Tools 2015': https://marketplace.visualstudio.com/items?itemName=AndreiDzimchuk.ExperimentalTools

VS2017 version called 'Experimental Tools 2017' is available here: https://marketplace.visualstudio.com/items?itemName=AndreiDzimchuk.ExperimentalTools2017

**Comment by devtrix** [comment]
Thank you for your prompt attention.  Works great!
