### ISSUE TITLE
Namespace vs file path analyzer doesn't seem to work.

### ISSUE THREAD

**Issue by JeffRausch** [dzimchuk/experimental-tools#12]
### Installed product versions
- Visual Studio: 2017 Professional - 15.2 (26430.14) Release
- This extension: 0.8.80

### Description
The "Namespace vs file path analyzer" functionality doesn't seem to work.

### Steps to recreate
1. Installed the extension and restarted Visual Studio.
2. Modified the namespace on a file to not match the base namespace & file path.
 - Project Default Namespace: MyTestApp.Hello.API
 - Correct Class Namespace: MyTestApp.Hello.API
 - Namespaces I tried changing to:
    - MyTestApp.Hello.API.Test
    - MyTestApp.Hello.API2.Test
    - MyTestApp.Hello.API2.Test4
    - MyTestApp.Hello2.API

### Current behavior
I tried building the project and also restarting VS with the changed namespaces and none of them caused the name to show any squiggly line errors and didn't show the light bulb on the left when selected.  

### Expected behavior
I assume the namespace text should at least show underlined as I see in the documentation page: 
[Docs](https://github.com/dzimchuk/experimental-tools/tree/master#namespace-vs-file-path-analyzer-and-code-fix)
I have confirmed that the extension is enabled and the feature "Change namespace to match file path" was enabled (all features were enabled).  I tried disabling the feature and then re-enabling the feature and that did not fix it.  I also tried reinstalling the extension.  
I did try the guid replace ("nguid" + tab) and that worked fine so I know the extension is installed and working. 
Thanks!

**Comment by JeffRausch** [comment]
I also just tried the latest build (0.8.83) and it did not seem to fix the issue.
Thanks!

**Comment by dzimchuk** [comment]
@JeffRausch Please try the latest [CI build](http://vsixgallery.com/extension/fe00c281-eed0-4c6e-901b-d8b845c82e35/) (0.8.86) and see if it works for you.

**Comment by JeffRausch** [comment]
Works as expected now.  Thanks!
One question/request... is there any way to check a whole project for namespace issues and either automatically fix or just list ones that don't match the path?

**Comment by JeffRausch** [comment]
Ignore my last comment.  I forgot that those do show as build warnings in the errors window so that's good enough for us.

Thanks again!
