### ISSUE TITLE
Incorrect braces removing

### ISSUE THREAD

**Issue by eltoby** [dzimchuk/experimental-tools#13]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 0.9.88

### Description
Unsafe refactoring due to incorrect braces removing. Changes my code behaviour.

### Steps to recreate
Here's an example
[IncorrectBracesRemoving.zip](https://github.com/dzimchuk/experimental-tools/files/1228357/IncorrectBracesRemoving.zip)

### Current behavior
Remove braces makes else statement from an if statement go to another if statement.

### Expected behavior
Remove braces shouldn't be proposed in this cases.

**Comment by dzimchuk** [comment]
Fixed in 1.0
Please check the latest build!
