### ISSUE TITLE
RootNamespace not honored

### ISSUE THREAD

**Issue by Tasteful** [dzimchuk/experimental-tools#16]
### Installed product versions
- Visual Studio: 15.5.7
- This extension: 1.1.95

### Description
Have a project file that has `RootNamespace` set to something that differ from the project name. 

### Steps to recreate
Example `<RootNamespace>Company</RootNamespace>` in the `Company.Abstractions.csproj`-file. Create a file, in a subdirectory `Demo` the namespace for the file should now be using `Company.Demo`-namespace.

### Current behavior
Warning about `ET002` that namespace does not match the path.

### Expected behavior
No warning about `ET002` due to the `RootNamespace`-setting.

**Comment by dzimchuk** [comment]
@Tasteful Did you reload the project after changing its `RootNamespace`? Currently ET can only detect the namespace when the project is loaded by parsing its .csproj file.

**Comment by Tasteful** [comment]
@dzimchuk That can be the case. When I check one of the files now I don't get the warning and I don't remember today what exactly I was doing in February.

Will it be possible to attach a trigger to reload that information when the `csproj`-file is changed?

**Comment by dzimchuk** [comment]
@Tasteful Yes, it may be a possible option..

**Comment by Tasteful** [comment]
Still getting this error, even after installing VS 15.8.2 and cleaning the `.vs` folder. Now I run the `1.2.108` build of the `Experimental tools`

**Comment by dzimchuk** [comment]
@Tasteful I've improved namespace tracking in v1.3.0 and now it should be able to detect changes to the default namespace on the fly without needing to reload a solution. You will need to re-open files though as VS seems to cache analyzers' results.

**Comment by dzimchuk** [comment]
@Tasteful is this issue still relevant?

**Comment by Tasteful** [comment]
I will check if the problem still exists, will come back during the week.

**Comment by Tasteful** [comment]
I don't have any problem for the moment so we can close this.
