### ISSUE TITLE
System.IO.FileNotFoundException when loading the package

### ISSUE THREAD

**Issue by jpozo20** [dzimchuk/experimental-tools#19]
### Installed product versions
- Visual Studio: 2017 Enterprise v15.9.5
- This extension: v1.3.0

### Description
When Visual Studio loads a solution, a warning message appears saying there was an error with the extension

### Steps to recreate
1.Install ExperimentalTools
2. Load a Solution
3. A warning message appears
![image](https://user-images.githubusercontent.com/9166182/51841870-fa144b80-22e5-11e9-87ab-7e9e5be0ecc3.png)

### Current behavior
A warning message appears on Visual Studio indicating there may be a problem with the exception

### Expected behavior
The extension should'nt cause an exception on startup
Attached is the ActivityLog.xml generated by Visual Studio, changed the extension to txt so GitHub doesn't complain:

[ActivityLog.txt](https://github.com/dzimchuk/experimental-tools/files/2803341/ActivityLog.txt)

**Comment by dzimchuk** [comment]
@jpozo20 This should be fixed in 1.3.2. Please let me know if everything runs great now.
