### ISSUE TITLE
Keyboard shortcut for locating the files does not work.

### ISSUE THREAD

**Issue by Mrsevic** [dzimchuk/experimental-tools#24]
### Installed product versions
- Visual Studio: [2019 Professional latest stable version 16.5.4]
- This extension: [1.3.3]

### Description
Locate file in the solution explorer does not work.

### Steps to recreate
1. Try to locate the file in the solution explorer pressing the usual key combination.

### Current behavior
Nothing is happening(neither I see error in the solution explorer.

### Expected behavior
It should open the solution explorer and highlight the file that is currently opened. 

### Side note:
The issue started happening since the latest update. Thanks

**Comment by dzimchuk** [comment]
Shift+Alt+L is used for a bunch of other built-in VS commands:

![image](https://user-images.githubusercontent.com/3907708/123246779-d70a1800-d4ee-11eb-82d8-3de2007db7f8.png)

And even if we assign it to the Locate In Solution Explorer command it does not work. I believe the first 2 commands are the culprit as Shift+Alt+L is the first combination they expect and the way VS works it prioritizes them so they can wait for the second combination.

We'll need to come up with another default. Setting it to just 'Alt + L' works fine.

**Comment by dzimchuk** [comment]
Switched to Alt+L as of 1.3.4
